### ISSUE TITLE
Fix scraping code

### ISSUE THREAD

**Issue by aziff** [aziff/cta-project#1]
These are the things that need to be done with the scraping code:
1. Test code as it stands (especially looking at the new number of requests due to including more stops)
2. Abstract code as much as possible so that it is more efficient. Especially in the main function.
3. Allow for contingencies, e.g., what should the code do when there are "No parameters found" in the xml?
3. Write code to stitch together .csv files that are created

1/19/16 -- Testing code today (todo item 1)

**Comment by jorgelgarcia** [comment]
2/14/16 -- 2 and the second 3 are complete. Allowing for contingencies is something that still needs to be done, as well as making sure the code automatically runs on the servers correctly.

**Comment by aziff** [comment]
2/14/16 -- 2 and the second 3 are done. Allowing for contingencies is something that still needs to be done as well as coordinating with the server guys to ensure that the code runs automatically (using crontab)
